<?php

/**
 * This is the model base class for the table "foto".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Foto".
 *
 * Columns in table "foto" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idfoto
 * @property string $caminho
 * @property boolean $ativo
 * @property integer $idprod
 *
 */
abstract class BaseFoto extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'foto';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Foto|Fotos', $n);
	}

	public static function representingColumn() {
		return 'caminho';
	}

	public function rules() {
		return array(
			array('idfoto', 'required'),
			array('idfoto, idprod', 'numerical', 'integerOnly'=>true),
			array('caminho', 'length', 'max'=>255),
			array('ativo', 'safe'),
			array('caminho, ativo, idprod', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idfoto, caminho, ativo, idprod', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idfoto' => Yii::t('app', 'Idfoto'),
			'caminho' => Yii::t('app', 'Caminho'),
			'ativo' => Yii::t('app', 'Ativo'),
			'idprod' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idfoto', $this->idfoto);
		$criteria->compare('caminho', $this->caminho, true);
		$criteria->compare('ativo', $this->ativo);
		$criteria->compare('idprod', $this->idprod);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}