<?php

/**
 * This is the model base class for the table "usuario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Usuario".
 *
 * Columns in table "usuario" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $idusuario
 * @property string $nome
 * @property string $cpf
 * @property string $rg
 * @property string $telefone
 * @property string $datanasc
 * @property string $email
 * @property string $senha
 * @property string $cidade
 * @property string $rua
 * @property string $estado
 *
 */
abstract class BaseUsuario extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'usuario';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Usuario|Usuarios', $n);
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('idusuario', 'required'),
			array('idusuario', 'numerical', 'integerOnly'=>true),
			array('nome, cpf, rg, telefone, email, senha, cidade, rua, estado', 'length', 'max'=>255),
			array('datanasc', 'safe'),
			array('nome, cpf, rg, telefone, datanasc, email, senha, cidade, rua, estado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idusuario, nome, cpf, rg, telefone, datanasc, email, senha, cidade, rua, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idusuario' => Yii::t('app', 'Idusuario'),
			'nome' => Yii::t('app', 'Nome'),
			'cpf' => Yii::t('app', 'Cpf'),
			'rg' => Yii::t('app', 'Rg'),
			'telefone' => Yii::t('app', 'Telefone'),
			'datanasc' => Yii::t('app', 'Datanasc'),
			'email' => Yii::t('app', 'Email'),
			'senha' => Yii::t('app', 'Senha'),
			'cidade' => Yii::t('app', 'Cidade'),
			'rua' => Yii::t('app', 'Rua'),
			'estado' => Yii::t('app', 'Estado'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idusuario', $this->idusuario);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('cpf', $this->cpf, true);
		$criteria->compare('rg', $this->rg, true);
		$criteria->compare('telefone', $this->telefone, true);
		$criteria->compare('datanasc', $this->datanasc, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('senha', $this->senha, true);
		$criteria->compare('cidade', $this->cidade, true);
		$criteria->compare('rua', $this->rua, true);
		$criteria->compare('estado', $this->estado, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}